version: '3.8'
services:
  nut-cli:
    image: ghcr.io/felixclements/nut:latest
    volumes:
      - /path/to/conf:/app/conf
      - /path/to/titledb:/app/titledb
      - /path/to/data:/data
    ports:
      - "9000:9000"
