name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push nut-gui
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: ghcr.io/${{ github.repository_owner }}/nut-gui:latest
    - name: Build and push nut-cli
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.cli
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: ghcr.io/${{ github.repository_owner }}/nut-cli:latest
